"""empty message

Revision ID: 446968bb3adb
Revises: 5e8ae71a96dd
Create Date: 2022-12-05 13:49:00.302307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446968bb3adb'
down_revision = '5e8ae71a96dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.drop_column('smoke')
        batch_op.drop_column('alcohol')
        batch_op.drop_column('other_drugs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_drugs', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('alcohol', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('smoke', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
